// <auto-generated />
namespace Demo_Login2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _15082021V2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_15082021V2));
        
        string IMigrationMetadata.Id
        {
            get { return "202108150211317_15082021V2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
